CC = gcc

GROUP = com.marstonstudio.crossusermedia
PACKAGE = $(GROUP).encoder

OBJECTS_SWIG = ../c/encoder.h
TARGET_SWIG = Encoder

OBJECTS_ASC2 = dist/$(TARGET_SWIG).as
TARGET_ASC2 = dist/$(TARGET_SWIG).abc

OBJECTS_CC = ../c/encoder.c
TARGET_CC = dist/encoder.swc

#OBJECTS_LIB = $(PACKAGE).Encoder
#TARGET_LIB = dist/encoder.swc

LDFLAGS = -L./dist/lib

LDLIBS = -lm -lavdevice -lavformat -lavfilter -lavcodec -lswresample -lswscale -lavutil

CFLAGS = -v \
	-I./dist/include \
	-emit-swc=$(PACKAGE)

all: program

program: $(OBJECTS_CC)

#	mkdir -p dist

#	@echo "**** generating SWIG classes ***"
#	$(SWIG) -v -as3 -includeall -ignoremissing \
#		-outdir dist \
#		-module $(TARGET_SWIG) \
#		$(OBJECTS_SWIG)

#		mv ../c/encoder_wrap.c ../dist/encoder_wrap.c


#	@echo "**** compiling SWIG classes ***"
#	$(ASC2) -AS3 \
#		-import $(FLASCC)/usr/lib/builtin.abc \
#		-import $(FLASCC)/usr/lib/playerglobal.abc \
#		$(OBJECTS_ASC2) \
#		-outdir dist

	@echo "**** compiling encoder classes ***"
	$(CC) $(CFLAGS)  dist/Encoder.abc ../c/encoder.c ../c/encoder_wrap.c -o $(TARGET_CC) $(LDFLAGS) $(LDLIBS)

#	@echo "**** packaging library ***"
#	$(COMPC) \
#		-include-libraries=$(TARGET_CC) \
#		-source-path=src -include-classes $(OBJECTS_LIB) \
#		-o $(TARGET_LIB)

install:
	mvn install:install-file -Dfile=$(TARGET_CC) \
		-DgroupId=$(GROUP) \
		-DartifactId=encoder \
		-Dversion=1.0-SNAPSHOT \
		-Dpackaging=swc \
		-DgeneratePom=true

clean:
	rm -f ../c/encoder_wrap.c
	rm -f dist/*.swc
	rm -f dist/*.as
	rm -f dist/*.abc
